# Generated by Django 5.1.2 on 2024-10-22 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("qr_generator", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Certificate Name"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="certificates/", verbose_name="Certificate File"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        verbose_name="File Hash",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "upload_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Upload Time"),
                ),
                (
                    "last_checked",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Checked"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(blank=True, null=True, verbose_name="Issue Date"),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="Expiry Date"),
                ),
                (
                    "verified",
                    models.BooleanField(default=False, verbose_name="Verified"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Version"),
                ),
                (
                    "previous_versions",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Previous Versions"
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(default=False, verbose_name="Approved"),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Approval Status",
                    ),
                ),
                (
                    "suspected_tampered",
                    models.BooleanField(
                        default=False, verbose_name="Suspected Tampered"
                    ),
                ),
                (
                    "certificate_qr",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificate",
                        to="qr_generator.certificateqr",
                        verbose_name="Certificate QR Code",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        limit_choices_to={"role": "supplier"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate",
                "verbose_name_plural": "Certificates",
                "indexes": [
                    models.Index(
                        fields=["supplier"], name="certificate_supplie_8a905b_idx"
                    ),
                    models.Index(
                        fields=["file_hash"], name="certificate_file_ha_7ac2ed_idx"
                    ),
                ],
            },
        ),
    ]
