# Generated by Django 5.1.2 on 2024-10-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operatorpermission",
            name="can_access_financials",
        ),
        migrations.RemoveField(
            model_name="operatorpermission",
            name="can_manage_certificates",
        ),
        migrations.RemoveField(
            model_name="operatorpermission",
            name="can_manage_notifications",
        ),
        migrations.RemoveField(
            model_name="operatorpermission",
            name="can_manage_orders",
        ),
        migrations.RemoveField(
            model_name="operatorpermission",
            name="can_manage_products",
        ),
        migrations.RemoveField(
            model_name="operatorpermission",
            name="can_manage_reports",
        ),
        migrations.RemoveField(
            model_name="operatorpermission",
            name="can_manage_users",
        ),
        migrations.RemoveField(
            model_name="predefinedadminright",
            name="can_access_financials",
        ),
        migrations.RemoveField(
            model_name="predefinedadminright",
            name="can_manage_certificates",
        ),
        migrations.RemoveField(
            model_name="predefinedadminright",
            name="can_manage_notifications",
        ),
        migrations.RemoveField(
            model_name="predefinedadminright",
            name="can_manage_orders",
        ),
        migrations.RemoveField(
            model_name="predefinedadminright",
            name="can_manage_products",
        ),
        migrations.RemoveField(
            model_name="predefinedadminright",
            name="can_manage_reports",
        ),
        migrations.RemoveField(
            model_name="predefinedadminright",
            name="can_manage_users",
        ),
        migrations.AddField(
            model_name="operatorpermission",
            name="app_level_permissions",
            field=models.ManyToManyField(
                blank=True, to="auth.permission", verbose_name="App-Level Permissions"
            ),
        ),
        migrations.AddField(
            model_name="operatorpermission",
            name="view_only",
            field=models.BooleanField(default=False, verbose_name="View Only"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="approval_status",
            field=models.CharField(
                default="pending", max_length=10, verbose_name="Approval Status"
            ),
        ),
    ]
