# Generated by Django 5.1.2 on 2024-10-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ar", "Arabic")],
                default="en",
                max_length=7,
                verbose_name="Language",
            ),
        ),
    ]
