# Generated by Django 5.1.2 on 2024-10-22 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_operatorpermission_can_access_financials_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PredefinedAdminRight",
        ),
    ]
