# Generated by Django 5.1.2 on 2024-10-23 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_delete_predefinedadminright"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("qr_generator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Approval Status",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?1?\\d{9,15}$", "Enter a valid phone number."
                    )
                ],
                verbose_name="Phone Number",
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["is_active"], name="accounts_cu_is_acti_2885e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["approval_status"], name="accounts_cu_approva_74d667_idx"
            ),
        ),
    ]
