# Generated by Django 5.1.2 on 2024-10-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_customuser_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Last Name"
            ),
        ),
    ]
