# Generated by Django 5.1.2 on 2024-10-23 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_customuser_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?1?\\d{9,15}$", "Enter a valid phone number."
                    )
                ],
                verbose_name="Phone Number",
            ),
        ),
    ]
