# Generated by Django 5.1.2 on 2024-10-24 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_customuser_groups_alter_customuser_language_and_more"),
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "operator"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tickets",
                to="accounts.customuser",
                verbose_name="Assigned Operator",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="supplier",
            field=models.ForeignKey(
                limit_choices_to={"role": "supplier"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="accounts.customuser",
                verbose_name="Supplier",
            ),
        ),
        migrations.AlterField(
            model_name="ticketreply",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_replies",
                to="accounts.customuser",
                verbose_name="Author",
            ),
        ),
    ]
