# Generated by Django 5.1.2 on 2024-10-22 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Action Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Is Default Action"
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Action",
                "verbose_name_plural": "Approval Actions",
                "indexes": [
                    models.Index(fields=["name"], name="approval_ap_name_742791_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("supplier", "Supplier"),
                            ("certificate", "Certificate"),
                            ("product", "Product"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Entity Type",
                    ),
                ),
                ("entity_id", models.PositiveIntegerField(verbose_name="Entity ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Approval Status",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed At"
                    ),
                ),
                (
                    "request_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Request Time"
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Comments")),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requester",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approvals_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Request",
                "verbose_name_plural": "Approval Requests",
            },
        ),
        migrations.CreateModel(
            name="ApprovalLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=10,
                        verbose_name="Previous Status",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=10,
                        verbose_name="New Status",
                    ),
                ),
                (
                    "action_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Action Time"),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Comments")),
                (
                    "action_taken_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Action Taken By",
                    ),
                ),
                (
                    "approval_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="approval.approvalrequest",
                        verbose_name="Approval Request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Log",
                "verbose_name_plural": "Approval Logs",
            },
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["entity_id", "entity_type"],
                name="approval_ap_entity__521231_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(fields=["status"], name="approval_ap_status_c222b0_idx"),
        ),
        migrations.AddIndex(
            model_name="approvallog",
            index=models.Index(
                fields=["approval_request"], name="approval_ap_approva_8747f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvallog",
            index=models.Index(
                fields=["action_time"], name="approval_ap_action__28fe01_idx"
            ),
        ),
    ]
