# Generated by Django 5.1.2 on 2024-10-24 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_customuser_groups_alter_customuser_language_and_more"),
        ("approval", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvallog",
            name="action_taken_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approval_actions",
                to="accounts.customuser",
                verbose_name="Action Taken By",
            ),
        ),
        migrations.AlterField(
            model_name="approvalrequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_requests",
                to="accounts.customuser",
                verbose_name="Requester",
            ),
        ),
        migrations.AlterField(
            model_name="approvalrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approvals_reviewed",
                to="accounts.customuser",
                verbose_name="Reviewed By",
            ),
        ),
    ]
