# Generated by Django 5.1.2 on 2024-10-22 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Task Name")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("certificate_expiry", "Certificate Expiry Check"),
                            ("profile_verification", "Profile Verification Check"),
                            ("email_verification", "Email Verification Check"),
                            ("profile_completion", "Profile Completion Check"),
                            ("inactive_users", "Inactive User Check"),
                            ("unresolved_tickets", "Unresolved Ticket SLA Check"),
                        ],
                        max_length=50,
                        verbose_name="Task Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Run At"
                    ),
                ),
                (
                    "custom_dates",
                    models.JSONField(
                        blank=True,
                        help_text="Custom date intervals in days, e.g., {'days': [30, 60, 90, 180]}",
                        null=True,
                        verbose_name="Custom Date Intervals",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "notification_rule",
                    models.ForeignKey(
                        help_text="Select a rule for triggering notifications.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_tasks",
                        to="notifications.notificationrule",
                        verbose_name="Notification Rule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("certificate_expiry", "Certificate Expiry Date"),
                            ("profile_completion", "Profile Completion"),
                            ("email_verification", "Email Verification"),
                            ("user_activity", "User Activity"),
                            ("phone_verification", "Phone Verification"),
                            ("role_assignment", "User Role Assignment"),
                            ("custom", "Custom Condition"),
                        ],
                        max_length=50,
                        verbose_name="Condition Type",
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("<", "Less Than"),
                            ("<=", "Less Than or Equal"),
                            ("=", "Equal"),
                            (">=", "Greater Than or Equal"),
                            (">", "Greater Than"),
                            ("in", "In Range"),
                        ],
                        max_length=20,
                        verbose_name="Operator",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Value to compare with",
                        max_length=255,
                        verbose_name="Value",
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True,
                        help_text="Any additional metadata or configurations for the condition",
                        null=True,
                        verbose_name="Additional Data",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="task_scheduler.scheduledtask",
                        verbose_name="Scheduled Task",
                    ),
                ),
            ],
        ),
    ]
