# Generated by Django 5.1.2 on 2024-10-24 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_customuser_groups_alter_customuser_language_and_more"),
        ("task_scheduler", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledtask",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.customuser",
                verbose_name="Created By",
            ),
        ),
    ]
