# Generated by Django 5.1.2 on 2024-10-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qr_generator", "0002_alter_certificateqr_qr_code_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificateqr",
            name="qr_code_image",
            field=models.ImageField(
                blank=True,
                default=1,
                upload_to="qr_codes/certificates/",
                verbose_name="QR Code Image",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productqr",
            name="qr_code_image",
            field=models.ImageField(
                blank=True,
                default=1,
                upload_to="qr_codes/products/",
                verbose_name="QR Code Image",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supplierqr",
            name="qr_code_image",
            field=models.ImageField(
                blank=True,
                upload_to="qr_codes/suppliers/",
                verbose_name="QR Code Image",
            ),
        ),
    ]
