# Generated by Django 5.1.2 on 2024-10-24 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_customuser_groups_alter_customuser_language_and_more"),
        ("qr_generator", "0003_alter_certificateqr_qr_code_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificateqr",
            name="supplier",
            field=models.ForeignKey(
                limit_choices_to={"role": "supplier"},
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.customuser",
                verbose_name="Supplier",
            ),
        ),
        migrations.AlterField(
            model_name="productqr",
            name="supplier",
            field=models.ForeignKey(
                limit_choices_to={"role": "supplier"},
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.customuser",
                verbose_name="Supplier",
            ),
        ),
        migrations.AlterField(
            model_name="supplierqr",
            name="supplier",
            field=models.OneToOneField(
                limit_choices_to={"role": "supplier"},
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.customuser",
                verbose_name="Supplier",
            ),
        ),
    ]
