# Generated by Django 5.1.2 on 2024-10-22 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification_templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('voice', 'Voice Call')], max_length=20, unique=True, verbose_name='Notification Method')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Notification Method',
                'verbose_name_plural': 'Notification Methods',
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Rule Name')),
                ('trigger', models.CharField(choices=[('expiry', 'Certificate Expiry'), ('approval', 'Certificate Approval'), ('reminder', 'Reminder'), ('custom', 'Custom Rule'), ('email_verification', 'Email Verification Reminder'), ('profile_completion', 'Profile Completion Reminder'), ('task', 'Task Reminder')], max_length=50, verbose_name='Trigger')),
                ('condition', models.CharField(blank=True, help_text="Custom condition logic, e.g., 'expiry_date < today + 3 months'", max_length=255, verbose_name='Condition')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('priority', models.PositiveIntegerField(default=1, help_text='Higher numbers indicate higher priority.', verbose_name='Priority')),
                ('email_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_rules', to='notification_templates.emailtemplate', verbose_name='Email Template')),
                ('notification_methods', models.ManyToManyField(related_name='notification_rules', to='notifications.notificationmethod', verbose_name='Notification Methods')),
                ('sms_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_rules', to='notification_templates.smstemplate', verbose_name='SMS Template')),
                ('voice_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_rules', to='notification_templates.voicetemplate', verbose_name='Voice Template')),
            ],
            options={
                'verbose_name': 'Notification Rule',
                'verbose_name_plural': 'Notification Rules',
            },
        ),
        migrations.CreateModel(
            name='NotificationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_time', models.DateTimeField(help_text='Time to send the notification', verbose_name='Schedule Time')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Is Recurring')),
                ('recurrence_interval', models.PositiveIntegerField(default=0, help_text='Interval in days for recurring notifications', verbose_name='Recurrence Interval (days)')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Sent At')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='notifications.notificationrule', verbose_name='Notification Rule')),
            ],
            options={
                'verbose_name': 'Notification Schedule',
                'verbose_name_plural': 'Notification Schedules',
            },
        ),
        migrations.CreateModel(
            name='RecordedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Message Name')),
                ('message_file', models.FileField(blank=True, null=True, upload_to='notifications/voice/', verbose_name='Recorded Voice Message')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Recorded Message',
                'verbose_name_plural': 'Recorded Messages',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email Notifications')),
                ('sms_notifications', models.BooleanField(default=True, verbose_name='SMS Notifications')),
                ('voice_notifications', models.BooleanField(default=False, verbose_name='Voice Notifications')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=5, verbose_name='Preferred Language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Notification Preferences',
                'verbose_name_plural': 'User Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20, verbose_name='Status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('message_id', models.CharField(blank=True, max_length=100, verbose_name='Message ID')),
                ('additional_data', models.JSONField(blank=True, null=True, verbose_name='Additional Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationmethod', verbose_name='Notification Method')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationrule', verbose_name='Notification Rule')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'indexes': [models.Index(fields=['user'], name='notificatio_user_id_c291d5_idx'), models.Index(fields=['status'], name='notificatio_status_d92267_idx')],
            },
        ),
    ]
