# Generated by Django 5.1.2 on 2024-10-22 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20, verbose_name='Status')),
                ('message_id', models.CharField(blank=True, max_length=100, verbose_name='Message ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('additional_data', models.JSONField(blank=True, null=True, verbose_name='Additional Data')),
                ('method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationmethod', verbose_name='Notification Method')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationrule', verbose_name='Notification Rule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_history', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification History',
                'verbose_name_plural': 'Notification Histories',
            },
        ),
        migrations.DeleteModel(
            name='RecordedMessage',
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['user'], name='notificatio_user_id_93d024_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['method'], name='notificatio_method__0243cb_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['status'], name='notificatio_status_a89757_idx'),
        ),
    ]
