# Generated by Django 5.1.2 on 2024-10-24 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_customuser_groups_alter_customuser_language_and_more"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="accounts.customuser",
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="notificationhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_history",
                to="accounts.customuser",
                verbose_name="User",
            ),
        ),
    ]
