# Generated by Django 5.1.2 on 2024-10-24 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TwilioMessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[("sms", "SMS"), ("voice", "Voice Call")],
                        max_length=10,
                        verbose_name="Message Type",
                    ),
                ),
                (
                    "message_sid",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Message SID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Message"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sent At"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Twilio Message Log",
                "verbose_name_plural": "Twilio Message Logs",
                "indexes": [
                    models.Index(
                        fields=["user"], name="twilio_app__user_id_8f1c64_idx"
                    ),
                    models.Index(
                        fields=["status"], name="twilio_app__status_7e00d8_idx"
                    ),
                    models.Index(
                        fields=["sent_at"], name="twilio_app__sent_at_2d6d4b_idx"
                    ),
                ],
            },
        ),
    ]
