# Generated by Django 5.1.2 on 2024-10-22 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='twiliomessagelog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='twiliomessagelog',
            index=models.Index(fields=['sent_at'], name='twilio_app__sent_at_2d6d4b_idx'),
        ),
    ]
